env:
    MANIFEST: https://github.com/Spark-Rom/manifest -b pyro
    DEVICE: fleur
    OEM: xiaomi
    DT_LINK: https://github.com/ShazuxD/device_xiaomi_fleur
    DT_PATH: device/android/vendor-blobs/vendor_xiaomi_miatoll.git
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/ArrowOS-Devices/android_kernel_xiaomi_sm6250.git
    PLATFORM: sm6250
    KT_PATH: kernel/$OEM/$PLATFORM
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: spark_${DEVICE}-userdebug
    OUTPUT: PixelExperience*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G



  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 -u $MANIFEST
      - repo sync -j4 --force-sync --no-tags --no-clone-bundle
      - git clone https://github.com/ShazuxD/device_xiaomi_fleur --depth=1 -b 13 device/xiaomi/fleur
      - git clone https://github.com/ShazuxD/vendor_xiaomi_fleur --depth=1 -b 13 vendor/xiaomi/fleur
      - git clone https://github.com/PixelExperience/device_mediatek_sepolicy_vndr --depth=1 device/mediatek/sepolicy_vndr
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - ./bu*
